apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dgo1edjen-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dgo1edjen-java-quarkus-gitops